POST http://localhost:8000/api/auth/register.php
Content-Type: application/json

{
  "name": "API-Centric Use",
  "username": "testuser",
  "email": "newAapi@test.com",
  "password": "Test1234"
}

####
POST http://localhost:8000/api/auth/login.php 
Content-Type: application/json 

{
  "username":"apiuse",
  "password":"Backend1234"
}


# GET http://localhost:8000/api/medication.php
# Authorization: Bearer "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpYXNzaXN0X2JhY2tlbmQiLCJhdWQiOiJtZWRpYXNzaXN0X2Zyb250ZW5kIiwiaWF0IjoxNzQzNjExNzgyLCJleHAiOjE3NDM2MTUzODIsInN1YiI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciJ9.LR0FAcSyyjsZssvOfmqSdZ6H0nf6os8a5R2kerPMYOU"
# Accept: application/json

# POST http://localhost:8000/api/medication.php
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpYXNzaXN0X2JhY2tlbmQiLCJhdWQiOiJtZWRpYXNzaXN0X2Zyb250ZW5kIiwiaWF0IjoxNzQzNjEwNjQwLCJleHAiOjE3NDM2MTQyNDAsInN1YiI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciJ9.OVq-UdSoE0QoAcngCPoIH2rFSmeNYoUMmVk8Rjhavkw
# Accept: application/json

# {
#   "name": "Ibuprofen",
#   "dosage": "200mg"
# }
##

GET http://localhost:8000/api/test.php
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpYXNzaXN0X2JhY2tlbmQiLCJhdWQiOiJtZWRpYXNzaXN0X2Zyb250ZW5kIiwiaWF0IjoxNzQzNjExNzgyLCJleHAiOjE3NDM2MTUzODIsInN1YiI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciJ9.LR0FAcSyyjsZssvOfmqSdZ6H0nf6os8a5R2kerPMYOU
Accept: application/json